finalize transition to crates.io (#481)
This fixes the panic caused by the switch to crates.io versions of
embassy crates.

```
1308.443201 [ERROR] panicked at C:\Users\febalbi\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\embassy-executor-0.7.0\src\raw\waker.rs:38:9:
Found waker not created by the Embassy executor. `embassy_time::Timer` only works with the Embassy executor. (panic_probe panic-probe-0.3.2/src/lib.rs:104)
```

---------

Signed-off-by: Felipe Balbi <febalbi@microsoft.com>
Co-authored-by: Felipe Balbi <febalbi@microsoft.com>